export default {
	px: {
		"width": "width",
		"height": "height",
		"left": "left",
		"right": "right",
		"top": "top",
		"bottom": "bottom",
		"margin": "margin",
		"padding": "padding",
		"marginTop": "marginTop",
		"margin-top": "margin-top",
		"marginBottom": "marginBottom",
		"margin-bottom": "margin-bottom",
		"marginLeft": "marginLeft",
		"margin-left": "margin-left",
		"marginRight": "marginRight",
		"margin-right": "margin-right",
		"paddingTop": "paddingTop",
		"padding-top": "padding-top",
		"paddingBottom": "paddingBottom",
		"padding-bottom": "padding-bottom",
		"paddingLeft": "paddingLeft",
		"padding-left": "padding-left",
		"paddingRight": "paddingRight",
		"padding-right": "padding-right",
		"offsetX": "offsetX",
		"offsetY": "offsetY",
		"font-size": "font-size",
		"fontSize": "fontSize",
		"text-indent": "text-indent",
		"textIndent": "textIndent",
		"line-height": "line-height",
		"lineHeight": "lineHeight"
	},
	noUnit: {
		"opacity": "opacity",
		"zIndex": "zIndex",
		"z-index": "z-index"
	}
}